name: Interesting Stuff Test
favicon: null
layout_spectrum: 0.25242
typography_spectrum: 0.5891996033024043
title: Test Title Area
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bcc9bf'
    - '#010c0e'
    - '#6fa5bf'
    - '#4e6462'
    - '#9b6b3c'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
